cosmetics

diff --git a/server/sxscripts/sbin/sxsetup.in b/server/sxscripts/sbin/sxsetup.in
--- a/server/sxscripts/sbin/sxsetup.in
+++ b/server/sxscripts/sbin/sxsetup.in
@@ -110,7 +110,7 @@ if [ "$INFO_GIVEN" = "yes" -o "$UPGRADE_GIVEN" = "yes" ]; then
 	    "@sbindir@/sxserver" stop
 	    "@sbindir@/sxadm" node $OWNERFLAG --upgrade "$SX_DATA_DIR"
 	    if [ $? -ne 0 ]; then
-		echo "Failed to upgrade the local node"
+		echo "ERROR: Failed to upgrade the local node"
 		"@sbindir@/sxserver" start
 		exit 1
 	    fi
@@ -118,23 +118,35 @@ if [ "$INFO_GIVEN" = "yes" -o "$UPGRADE_GIVEN" = "yes" ]; then
 	else
 	    echo "Local node is up-to-date."
 	fi
-
-        "@sbindir@/sxadm" cluster --upgrade "sx://admin@$SX_CLUSTER_NAME"
+	OUT=`mktemp /tmp/sxsetupXXXXXXX`
+	if [ $? -ne 0 ]; then
+	    echo "ERROR: Failed to create temporary file"
+	    exit 1
+	fi
+        "@sbindir@/sxadm" cluster --upgrade "sx://admin@$SX_CLUSTER_NAME" > $OUT 2>&1
 	RET=$?
 	if [ $RET -eq 2 ]; then
+	    cat $OUT
 	    echo
 	    echo "All components of the cluster are up-to-date!"
+	    rm $OUT
 	    exit 0
 	elif [ $RET -ne 0 ]; then
 	    echo
-	    echo "Could not upgrade the cluster at this point. Please run sxsetup --upgrade"
-	    echo "again when all other nodes are locally updated and online. The cluster"
-	    echo "should also get upgraded automatically after the last node is locally upgraded."
+	    echo "Could not upgrade the remote cluster data at this point. Please run"
+	    echo "sxsetup --upgrade again when all other nodes are locally upgraded and"
+	    echo "online. The cluster should also get upgraded automatically after the"
+	    echo "last node is locally upgraded."
+	    rm $OUT
 	    exit 1
 	fi
+	echo
+	echo "Upgrading remote cluster data..."
+	cat $OUT
+	rm $OUT
         "@sbindir@/sxadm" cluster --info "sx://admin@$SX_CLUSTER_NAME"
 	echo
-	echo "Cluster upgrade started. You can monitor the progress by running:"
+	echo "Remote upgrade started. You can monitor the progress by running:"
 	echo "@sbindir@/sxadm cluster --info sx://admin@$SX_CLUSTER_NAME"
 	exit 0
     fi
